### ISSUE TITLE
Upgrade to VueJS v3

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/apply#1002]
Our admin app has recently been upgraded by @drieJAC to use Vue 3 instead of Vue 2.

Lessons learned and some useful pointers have been documented here:
https://github.com/jac-uk/admin/blob/main/VUE3_UPGRADE.md

Please upgrade our Apply app to use Vue 3 instead of Vue 2.

**Note**: 
 - Refer to the upgrade notes (and source code) in Admin for any help
 - @tomlovesgithub will be upgrading Assessments app and @halcyonJAC will be upgrading Apply so please do talk to each other and co-ordinate efforts if you like
 - @drieJAC is also available to help answer any questions or advise on best path forwards

**Comment by warrensearle** [comment]
Following UT issues have been identified with:

 - Character Checks
 - Applications being unlocked

Please see the UT document for full details:
https://docs.google.com/document/d/1nCZYzDLwWXTaU9BGp8Dxp05VkPfFbMZk/edit

**Comment by nickaddy** [comment]
@HalcyonJAC to set up test exercise and update how to test instructions for users.

**Comment by nickaddy** [comment]
@HalcyonJAC Can you look into these issues pls? Copying @warrensearle for info.

When I create an account and hit ‘Create account’ the button turns yellow, but the page does not progress. When I click again, I am signed in and the account has been created.

When applying for JAC00666 and go to the welsh posts section, nothing is displayed as below. If this is because welsh posts are not an option, why does this section display at all?

When applying for new vacancies for the first time, sections are marked as Done and Review Application is greyed out, but deadline has not passed, e.g. JAC00636 District Judge COPY 1

Wasn’t able to complete character consent check - all completed already
