### ISSUE TITLE
User directed to Create an Account page at Log-in

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/apply#1103]
Background
I have observed this previously, but thought it had been fixed in the Vue upgrade.

Description
When a user logs in, they should be directed to the homepage with links to Current vacancies, their applications, etc. However, on some occasions, the user is taken to the 'Create an Account' page on login - see screenshot below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26ea075afed443db913ba779f34a87275acffe78/image.png)

**Comment by warrensearle** [comment]
Currently we store the page the user is on when they click the sign in button, so we can send them back there when they have signed in.
So this might be because the user is on the 'Create an account' page and then clicks the Sign in button. 
If that's the case then we can handle this scenario and direct the user to the home (vacancies) page instead.

**Comment by nickaddy** [comment]
@HalcyonJAC This mirrors the work on Admin that Ko Wei is currently doing, hence he could pick this up in Jan.

**Comment by HalcyonJAC** [comment]
I have tested it and it seems that this issue has been fixed.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3l0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64adef20ba4453779033ad4b5809541661e08226/1103%20User%20directed%20to%20Create%20an%20Account%20page%20at%20Log-in.mp4)
