### ISSUE TITLE
JAC00006:  Change to the Salaried Part-time working help text

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#214]
**Is your feature request related to a problem? Please describe.**
We need to amend the help text for the SPTW help text on this exercise

**Describe the solution you'd like**
We need to change the wording to
"Part-time working is available for this role, it can only be accommodated by working full weeks and in block periods of at least six weeks."

**Describe alternatives you've considered**
To make the help text configurable for each exercise in future.  

**Additional context**

**Comment by Rebecca-mcknight1991** [comment]
@LaurenQurashi 

At present when the candidate gets to 'Set part-time working preferences' and selects 'Yes' they see the below:

![image.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/a1150541-2694-47d4-a634-c7e5ddf4659d)

What needs to happen instead is where it says 'part time working is available for this role' it needs a follow up sentence so instead it reads 

**Part time working preferences**

Part-time working is available for this role, it can only be accommodated by working full weeks and in block periods of at least six weeks.

They then just need a yes or no with the box saying 'With reference to the working patterns for this role, provide details of those you want to work to' to disappear. This is because there is only 1 working pattern so it is a simple Y/N.
