### ISSUE TITLE
Candidate can apply on an unopened exercise

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#249]
**Describe the bug**
A candidate was able to complete pages of any exercise for JAC0015 before it had officially opened.  

**To Reproduce**
1. Go to any open exercise 
2. Click on 'apply'
3. Click on any page
4. In a separate browser tab - go to the vacancy page and pick an exercise on the  Future applications list
5. Follow steps 2 and pick the same page as on the other tab
6.  From the url take the exercise reference code and copy it
7.  Copy the exercise reference code into the url on the original vacancy
8.  See the error

**Expected behavior**
 All the pages of an exercise should not be accessible until it is open for applications.

**Screenshots**
Feedback from a candidate
I am now struggling to get beyond the stage where I click review application despite having completed all of the tabs. I have however struggled to select the only option available (none) on the Jurisdiction Preferences section which may explain the problem.

I’m grateful for your assistance.

Test on a Mac with Chrome.

**Additional context**
Monika is aware of the issue and has a potential solution

**Comment by Rebecca-mcknight1991** [comment]
Discussed with @YaaL and @ClaireTroughtonJAC . And flagged by Senior Leadership and CEO. This needs to be a high priority to stop this from happening. Suspect candidates have a tab open before 1pm and they can then click apply after 1pm from this opened tab. 

Next exercises closing which we should try and get this fixed by:
Fee-paid Financially Qualified Members, First-tier Tribunal, Social Entitlement Chamber (Social Security and Child Support) **Closing 1pm 7 April**

Fee Paid Specialist Lay Members First-tier Tribunal Health Education and Social Care Chamber (Mental Health jurisdiction) and Mental Health Review Tribunal for Wales (MHRT Wales). **Closing 1pm 9 April**

Judge of the First-tier Tribunal **Closing 1pm 14 April**

**Comment by YaaL** [comment]
This has now been fixed.
Also includes preventing users from submitting an application if they started applying just before close time and tried to submit after the close time passed.
Plus in the last hour we're showing a countdown timer to let people know how much time they have left.
