### ISSUE TITLE
JAC00028:  Issue with working preferences displaying to candidate.

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/apply#303]
**Describe the bug**
Exercise JAC00028 has just launched but there is going to be an issue with candidates submitting their applications.

On the admin side there are no "working preferences" set up.  However, they are showing on the apply side.
We need to remove the option from the candidate side so that they can submit their applications.

**To Reproduce**
1. Go to 'apply'
2. Click on 'vacancies'
3. Select JAC00028 
4. Start application
5. Go to working preferences
5. Try to save and leave the screen

**Expected behavior**
Remove working preferences from the "apply for the role" list

**Screenshots**

Admin Side

![Screenshot 2020-06-16 at 13.22.12.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/451b943e-b6d6-43c0-baa8-b7c1cd021ade)

Apply side 
![Screenshot 2020-06-16 at 13.24.44.png](https://images.zenhubusercontent.com/5e3c2b35e9bf7c0ea1c2859a/17890b01-0e6e-4fa7-9ef2-79733bee0067)

**Comment by crablab** [comment]
I think this is a data issue. For this exercise, in the database `locationQuestion` is set to the string "None" and the test in `taskList` (and other places), as to whether to display these questions or not, is if `locationQuestion` is `Null` or not (which it isn't here).

(This also applies to `jurisidictionQuestion` in the same way)

**Proposed Resolution** 
- Modify the two fields (`locationQuestion` and `jurisdictionQuestion`) to be `Null`. This will allow candidates to progress the form. 
- We then need to find out how it was set to "None" rather than Null , which will be an Admin bug.

**Comment by warrensearle** [comment]
Thank you @crablab for a great commentary.

@Claire for this exercise the actual text “None” had been inserted in the question title fields.
Thus on Apply we are asking the candidate for their answer to the question “None”!
To not ask questions in Apply the team should simply empty the question title field(s) in Admin.
We have emptied the question title fields for JAC00028.
Please can you verify all is ok now for this exercise.

**Comment by ClaireTroughtonJAC** [comment]
Thanks @Warren Searle and @Hugh I have told the team directly.  I will also post in feedback.  I can confirm that its all working now.
