### ISSUE TITLE
Add any numbers of document to exercise downloads.

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/apply#675]
As a user l want to  use the others tab to upload more  document  while filling my application so that l can submit all the document that is required for the exercises.

Note: Others should appear underneath related content

![Display others.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/1388dd6a-7a04-4c36-a008-621e4768b75a)

This ticket is linked to #1066 that has already been developed and is live.   

The exercise downloads page needs to be redesigned.

There should be a drop down menu for the type of document you are uploading with the following options:
Job Description
Terms and Conditions
Competency Framework
Pension Information
Skills and Abilities Criteria
Independent Assessment Form
Candidate Assessment Form
Welsh Translation
Other

A box should then appear allowing them to name the document. They might need to upload more than one document under a heading e.g. 2 documents under Pension Information.

The number of documents upload-able should be unlimited. They just need to add another as they do now.

They should be able to save and continue but get a message at the top to save and continue anyway to check they want to save and continue anyway if one of the italics items if not uploaded.

To the candidate these documents still appear under 'Related Content'.

**Comment by KateMJAC** [comment]
Hello @joy-ade is it possible to explain the origin of this ticket, so I can see where it falls priority wise?

**Comment by warrensearle** [comment]
Hi @KateMJAC this is follow on work from ticket admin#1066 in which the Exercise Downloads part of Admin was re-written to allow more documents as well as 'other' documents. Following implementation of that work we realised there was no ticket for the related work of showing those downloads on the Apply site. Hence this ticket was born. It would seem sensible to implement this fairly soon so that the whole epic of work is done and dusted, though am unsure of the priority for our staff.
